### Login get Token
POST http://localhost:3000/gameApi/login HTTP/1.1
content-type: application/json

{
    "username": "Oskar",
    "password": ""
}

### TOURNAMENT CREATE
POST http://localhost:3000/gameApi/createTournament
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9za2FyIiwidXNlcklEIjo0LCJpYXQiOjE2NDUzNDI4MDcsImV4cCI6MTY0NTk0NzYwN30.pECNBcUwFH-tO7bho29MEa9ZvXuNGvdjmxOnLmQJ12U

{
    "title": "Tac Open",
    "begin": "2022-02-20 00:00:00+01",
    "deadline": "2022-03-04 00:00:00+01",
    "creationDates": ["2022-03-05 18:45:00+01", "2022-03-05 20:00:00+01", "2022-03-06 17:30:00+01", "2022-03-06 18:45:00+01", "2022-03-06 20:00:00+01"],
    "secondsPerGame": 4440,
    "nTeams": 32
}

### EXCHANGE USER
POST http://localhost:3000/gameApi/exchangeUser
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9za2FyIiwidXNlcklEIjo0LCJpYXQiOjE2MzAwODMxOTEsImV4cCI6MTYzMDY4Nzk5MX0.kQsiXOlX1uyzAJbVT23Wy5I4kjv_ISetTGpT8symNRs

{
    "usernameToReplace": "MrMilch",
    "usernameOfReplacement": "moonandsun",
    "tournamentID": "4"
}

### EXCHANGE USER
POST http://localhost:3000/gameApi/changeTournamentSignUpSize
content-type: application/json

{
    "tournamentID": "4",
    "nTeams": 16
}